# Generated by Django 5.0.4 on 2024-06-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='eventer',
            field=models.BooleanField(default=False, verbose_name='Доступ евентера'),
        ),
    ]
