# Generated by Django 5.0.4 on 2024-06-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_users_eventer'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='assist',
            field=models.BooleanField(default=False, verbose_name='Доступ ассистента'),
        ),
        migrations.AlterField(
            model_name='users',
            name='eventer',
            field=models.BooleanField(default=False, verbose_name='Доступ Ивент-команды'),
        ),
    ]
