# Generated by Django 5.0.4 on 2024-05-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Название локации')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL - автоматически загружается')),
                ('image', models.ImageField(blank=True,
                                            help_text='Фотография будет высвечиваться в категории локации.Загружайте хорошего качества. Желательно full-hd. ',
                                            upload_to='locations/%Y/%m/%d')),
                ('type',
                 models.CharField(choices=[('Красная', 'Красная'), ('Желтая', 'Желтая'), ('Зеленая', 'Зеленая')],
                                  help_text='Выставляйте статус локации. Для худзоны есть отдельная db!', max_length=40,
                                  null=True, verbose_name='Статус локации')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL - автоматически загружается')),
                ('name', models.CharField(max_length=50, verbose_name='Название худа')),
                ('description', models.TextField(max_length=500, verbose_name='Описание худзоны')),
                ('status',
                 models.CharField(choices=[('Красная', 'Красная'), ('Желтая', 'Желтая'), ('Зелёная', 'Зелёная')],
                                  max_length=30, verbose_name='Статус площадки')),
                ('faction_name', models.CharField(default='Свободна', max_length=120, verbose_name='Название фракции')),
                ('faction_link',
                 models.CharField(default='#', max_length=300, null=True, verbose_name='Ссылка на фракцию')),
                ('image', models.ImageField(help_text='Формат фотографии КВАДРАТ от 600x600', upload_to='images')),
                ('popular', models.BooleanField(default=False,
                                                help_text='Если место популярное. Оставляйте активным. В ином случае - нет. Влияет лишь на попадания в раздел популярно.',
                                                verbose_name='Популярность')),
                ('medical', models.BooleanField(default=False, help_text='Если медик присутствует - тыкайте на актив.',
                                                verbose_name='Присутствие медика')),
                ('technician',
                 models.BooleanField(default=False, help_text='Если медик присутствует - тыкайте на актив.',
                                     verbose_name='Присутствие техника')),
                ('salesman', models.BooleanField(default=False,
                                                 help_text='Если торгаш системный/игрок присутствует - тыкайте на актив.',
                                                 verbose_name='Присутствие торгаша')),
                ('location', models.ForeignKey(help_text='Выберите локацию на которой находится худзона',
                                               on_delete=django.db.models.deletion.PROTECT, related_name='Location',
                                               to='locations.location')),
            ],
            options={
                'verbose_name': 'Худ',
                'verbose_name_plural': 'Худ',
            },
        ),
    ]
