# Generated by Django 5.0.4 on 2024-06-04 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название мероприятия')),
                ('description', models.TextField(help_text='Краткое описание для игроков.', max_length=300,
                                                 verbose_name='Описания мероприятия')),
                ('type_event', models.CharField(choices=[('Глобальные мероприятия', 'Глобальные мероприятия'),
                                                         ('Локальные мероприятия', 'Локальные мероприятия')],
                                                default='Локальные мероприятия', max_length=30,
                                                verbose_name='Категория ивента')),
                ('vk', models.CharField(help_text='Контакт организатора мероприятия', max_length=120,
                                        verbose_name='Вконтакте')),
                ('full_description',
                 models.TextField(max_length=2500, verbose_name='Развёрнутое описание для проверяющего.')),
                ('property', models.TextField(verbose_name='Список имущества, которое понадобится')),
                ('nickname', models.CharField(max_length=60, verbose_name='Никнейм персонажа для выдачи')),
                ('status',
                 models.BooleanField(default=True, verbose_name='Доступна ли пользователям сайта мероприятие?')),
                ('archive', models.BooleanField(default=False, verbose_name='Мероприятие в архиве?')),
                ('type_status', models.CharField(
                    choices=[('На рассмотрение', 'На рассмотрение'), ('Одобрено', 'Одобрено'),
                             ('Отклонено', 'Отклонено')], default='На рассмотрение', max_length=40,
                    verbose_name='Статус мероприятия')),
                ('description_status', models.TextField(blank=True, max_length=300, null=True,
                                                        verbose_name='Если одобрено с пометками или отклонено, то объясните почему.')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятие',
            },
        ),
        migrations.CreateModel(
            name='ResponseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_link', models.CharField(max_length=300, verbose_name='Ссылка на фракцию')),
                ('vk',
                 models.CharField(help_text='Вконтакте фракционный', max_length=120, verbose_name='Ваш Вконтакте')),
                ('description', models.CharField(max_length=130, verbose_name='Описание / предпочтение в ивенте')),
                ('antispam',
                 models.BooleanField(default=False, verbose_name='Если мероприятие фейк - поставьте галочку')),
                ('archive', models.BooleanField(default=False, verbose_name='Архив')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                           related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявление на мероприятия',
                'verbose_name_plural': 'Заявление на мероприятии',
            },
        ),
    ]
