# Generated by Django 5.0.4 on 2024-06-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='archive',
            field=models.BooleanField(default=True, verbose_name='Мероприятие в архиве?'),
        ),
    ]
