# Generated by Django 5.0.4 on 2024-06-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0002_alter_events_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Мероприятие в архиве?'),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Доступна ли пользователям сайта мероприятие?'),
        ),
    ]
