# Generated by Django 5.0.4 on 2024-06-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0003_alter_events_archive_alter_events_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description_status',
            field=models.TextField(blank=True, default='', max_length=300, null=True,
                                   verbose_name='Если одобрено с пометками или отклонено, то объясните почему.'),
        ),
    ]
