# Generated by Django 5.0.4 on 2024-06-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0004_alter_events_description_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='property',
            field=models.TextField(max_length=300, verbose_name='Список имущества, которое понадобится'),
        ),
    ]
